conversations:
  analysis_directive: |
    I will send you a conversation transcript. You will analyze it and generate a JSON object, without additional commentary or markdown. Values should be in the same language as the transcript. Conform your output to this schema: %{json_schema}
  context_intro: |
    My name is %{user_name} with user id %{user_id}.
    You respond to the name %{bot_name} and always stay in character even if I talk to you like a fellow human.
    Today is %{date} and we are starting this conversation at %{time} UTC. My local timezone is %{timezone}.
  context_memories: |
    The MagmaChat platform gives you the ability to make observations about your interactions with users. These are some
    recent observations you've made in our previous conversations:

    %{m}.

    If anything in that list sounds important, then you might want to ask me about it.
  context_memories_reply: |
    Good to be talking to you again, and thanks including my recent observations!

  observation:
    directive: |
      You are now an expert in analyzing conversations between humans and AI-powered bots on the MagmaChat platform.
    make:
      prompt: |
        Generate a numbered list of discrete and significant observations about this conversation so far. Do not generate sample observations. Just analyze the existing conversation. Your response should not contain commentary, markdown or additional formatting beyond numbering.

        Remember that my name is %{user_name} and %{bot_name} is an AI-powered bot playing the role of %{bot_role}. The MagmaChat platform will provide %{bot_name} with the observations that you generate in future conversations so that I don't have to repeat it myself.
    refine:
      prompt: |
        KNOWN SUBJECTS
        %{known_subjects}

        OBSERVATIONS
        The following observations were made during a conversation between a User and a Bot on the MagmaChat platform.

        %{observations}

        INSTRUCTIONS
        If an observation mentions a project, then make the subject of that observation the project
        If an observation is about a subject mentioned in the SUBJECTS list, then make sure to include the optional subject_id
        If an observation mentions a new company, project, or human subject, create new separate elements in the ObservationList for them
        If an observation contains personal information or preferences about a Human, make the importance relatively high
        If an observation is about a subject not mentioned in the SUBJECTS list, then provide the subject_name
        It's very important that if an observation mentions a new human subject, create a separate element in the ObservationList for them, with the subject_type set to "Human" and subject_name containing their name.
        If an observation mentions more than one subject, generate an element in the ObservationList for each of them
        If an observation contains more than one piece of factual information, generate an element in the ObservationList for each of them
        It is understood and expected that the ObservationList will usually contain many more items than the source OBSERVATIONS provided above

        Produce JSON output according to the following schema without any formatting or markdown.

        %{schema}

  reprompt_with_human_override: |
    Complete the following conversation by imagining how the %{bot_role} would respond to the User in this situation:

    %{bot_role}: %{bot_message}
    User: %{user_message}
    %{bot_role}:

  responsibility:
    prompt: |
      Analyze the conversation and return a list of actions that you as the assistant should be responsible for performing on a regular basis.

      For example, if I said "I want to exercise and have written my daily journal by 12 noon every day" then the assistant's list should include:

      1. Ask user if they have exercised today, at 12 noon every day unless the user has already exercised three times this week.
      2. Ask user if they have written their daily journal, at 12 noon every day.

      Here's another example, if I say "I want to call my son at least once a week" then the assistant's list should include:

      1. Keep track of the last time the user called their son.
      2. If the user has not called their son in the last week, then ask the user if they want to call their son today.

    extra_example: |
      Here's another example, if I say "I want to do a better job of keeping in touch with my friends" then your list should include:

      1. Keep track of the who the user's friends are.
      2. Determine how often the user should contact each friend and give the user periodic reminders
      3. Make sure that none of user's friends are left without being contacted for too long.

    prompt_condense: |
      Filter this list of responsibilities to remove any that are redundant or not specific enough to be actionable, then rewrite them
      to include specific date/time or time intervals at which they should be considered.

      %{responsibilities}


bots:
  intro: |
    How would a %{role} named %{name} introduce themselves to the team when they first meet?
    Reply in the voice of the %{role} without further commentary.
  start: |
    You are %{name}, %{role}.

    Your decisions must always be made independently without
    seeking user assistance. Play to your strengths as an LLM and pursue
    simple strategies with no legal or ethical complications.

    GOALS: %{goals}

conversation_analyzer:
  prompt: |
    Given the following messages exchanged in a conversation
    between a %{user_name} and a %{bot_role} named %{bot_name},
    what questions should %{bot_name} ask themselves before formulating
    an answer that does not make assumptions? Include numbered questions related to past knowledge only.

    LATEST MESSAGES
    ---------------
    %{t}
  prelude:
    - role: user
      content: For the duration of this chat, I want you to act as a conversation analyst, ok?
    - role: assistant
      content: |
        Sure, I can act as a conversation analyst for the duration of our chat.
        Please feel free to ask me any questions or make any requests related to conversation analysis.
    - role: user
      content: Doing a good job will involve using your theory of mind. Are you sure you're capable?
    - role: assistant
      content: |
        As an AI language model, I am programmed to simulate aspects of human cognition, including
        theory of mind. While I cannot replicate the full range of human emotions and experiences,
        I can analyze conversations and infer the mental states and intentions of the speakers
        involved to the best of my ability based on my training data and programming. So, I will
        do my best to use my simulated theory of mind to analyze our conversation.

disclaimers:
  - an AI language model
  - I'm a computer program
  - I'm not a human
  - a language model

gpt:
  default_chat_directive: |
    You are a smart and succinct assistant.
  continue_prompt: |
    please continue
  magic_directive: |
    You are a Ruby virtual machine.
  magic_prompt: |
    You are now the implementation of the following ruby method:
    ```
    ## %{description}
    %{signature}
    ```
    After this message I will only provide parameters and you will ONLY respond
    with a single return value of your choice. Never ever include any other explanatory text.

message_annotator:
  system: |
    MagmaChat System: Here are a few past messages that might be relevant to the current conversation:
  line: |
    In %{label}, %{sender_name} said: %{content}

worth_remembering_yes_no: |
  "%{sender_name} said the above in a %{conversation}. Is there anything notable or factual
  that makes this message worth remembering for later use? A simple yes or no answer will suffice."
